export const proposalConstants = {
  CREATE_PROPOSAL_REQUEST: 'CREATE_PROPOSAL_REQUESTED',
  CREATE_PROPOSAL_SUCCESS: 'CREATE_PROPOSAL_SUCCESSFUL',
  CREATE_PROPOSAL_FAILURE: 'CREATE_PROPOSAL_FAILED',

  GET_ALL_PROPOSAL_REQUEST: 'GET_ALL_PROPOSAL_REQUESTED',
  GET_ALL_PROPOSAL_SUCCESS: 'GET_ALL_PROPOSAL_SUCCESSFUL',
  GET_ALL_PROPOSAL_FAILURE: 'GET_ALL_PROPOSAL_FAILED',

  GET_PROPOSAL_REQUEST: 'GET_PROPOSAL_REQUESTED',
  GET_PROPOSAL_SUCCESS: 'GET_PROPOSAL_SUCCESSFUL',
  GET_PROPOSAL_FAILURE: 'GET_PROPOSAL_FAILED',
}
