export const proposalConstants = {
  CREATE_PROPOSAL_REQUEST: 'CREATE_PROPOSAL_REQUESTED',
  CREATE_PROPOSAL_SUCCESS: 'CREATE_PROPOSAL_SUCCESSFUL',
  CREATE_PROPOSAL_FAILED: 'CREATE_PROPOSAL_FAILED',

  GET_ALL_PROPOSAL_REQUEST: 'GET_ALL_PROPOSAL_REQUESTED',
  GET_ALL_PROPOSAL_SUCCESS: 'GET_ALL_PROPOSAL_SUCCESSFUL',
  GET_ALL_PROPOSAL_FAILED: 'GET_ALL_PROPOSAL_FAILED',

  GET_PROPOSAL_REQUEST: 'GET_PROPOSAL_REQUESTED',
  GET_PROPOSAL_SUCCESS: 'GET_PROPOSAL_SUCCESSFUL',
  GET_PROPOSAL_FAILED: 'GET_PROPOSAL_FAILED',

  VOTE_PROPOSAL_REQUEST: 'VOTE_PROPOSAL_REQUESTED',
  VOTE_PROPOSAL_SUCCESS: 'VOTE_PROPOSAL_SUCCESSFUL',
  VOTE_PROPOSAL_FAILED: 'VOTE_PROPOSAL_FAILED'
}
