export const walletConstants = {
  CONNECT_REQUEST: 'WALLET_CONNECTION_REQUESTED',
  CONNECT_SUCCESS: 'WALLET_CONNECTION_SUCCESSFUL',
  CONNECT_FAILED: 'WALLET_CONNECTION_FAILED',

  CONTRIBUTION_REQUEST: 'CONTRIBUTION_REQUESTED',
  CONTRIBUTION_SUCCESS: 'CONTRIBUTION_SUCCESSFUL',
  CONTRIBUTION_FAILED: 'CONTRIBUTION_FAILED',

  ROLE_REQUEST: 'ROLE_ASSIGN_REQUESTED',
  ROLE_SUCCESS: 'ROLE_ASSIGN_SUCCESSFUL',
  ROLE_FAILED: 'ROLE_ASSIGN_FAILED',

  ROLE_CHECK_REQUEST: 'ROLE_CHECK_REQUESTED',
  ROLE_CHECK_SUCCESS: 'ROLE_CHECK_SUCCESSFUL',
  ROLE_CHECK_FAILED: 'ROLE_CHECK_FAILED'
}
