export const walletConstants = {
  CONNECT_REQUEST: 'WALLET_CONNECTION_REQUESTED',
  CONNECT_SUCCESS: 'WALLET_CONNECTION_SUCCESSFUL',
  CONNECT_FAILURE: 'WALLET_CONNECTION_FAILED',

  CONTRIBUTION_REQUEST: 'CONTRIBUTION_REQUESTED',
  CONTRIBUTION_SUCCESS: 'CONTRIBUTION_SUCCESSFUL',
  CONTRIBUTION_FAILURE: 'CONTRIBUTION_FAILED'
}
