export const proposalConstants = {
    GET_ALL_PROPOSAL_REQUEST: 'GET_ALL_PROPOSAL_REQUESTED',
    GET_ALL_PROPOSAL_SUCCESS: 'GET_ALL_PROPOSAL_SUCCESSFUL',
    GET_ALL_PROPOSAL_FAILURE: 'GET_ALL_PROPOSAL_FAILED',

    GET_PROPOSAL_REQUEST: 'GET_PROPOSAL_REQUESTED',
    GET_PROPOSAL_SUCCESS: 'GET_PROPOSAL_SUCCESSFUL',
    GET_PROPOSAL_FAILURE: 'GET_PROPOSAL_FAILED',
}